import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import VideoPlayer from '@/components/VideoPlayer'
import StreamingRoom from '@/components/StreamingRoom'


const inter = Inter({ subsets: ['latin'] })

export default function Stream() {
  return (
    <>
      <Head>
        <title>Upload Video</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <StreamingRoom roomId={"room1"} />
      
    </>
  )
}
